name: 'Arma 3 build mission'
description: 'Compile an arma 3 source mission directory into a binarized PBO file, using Arma 3 Tools'
inputs:

  source:
    description: 'Path to the directory containing the mission.sqm file'
    required: true

  target:
    description: 'Path to the directory where the action will output the pbo file'
    required: true

  briefingName:
    description: 'If not empty, will overwrite the mission briefingName before building the pbo'
    required: false
    default: ''

runs:
  using: composite
  steps:

    - shell: pwsh
      run: |
        $ActionArgs = @{
          Source = Join-Path -Path ${env:GITHUB_WORKSPACE} -ChildPath '${{ inputs.source }}'
          Target = Join-Path -Path ${env:GITHUB_WORKSPACE} -ChildPath '${{ inputs.target }}'
          BriefingName = ${{ inputs.briefingName }}
        }
        ${{ github.action_path }}/New-MissionPbo.ps1 @ActionArgs
